Make sure panic after fork reliably causes the test to fail
trifectatechfoundation/sudo-rs pull request #877
Opened 2024-10-11 14:09 UTC by bjorn3

I found this while investigating why the `close_the_universe` test was spuriously deadlocking on my system.

2024-10-14 15:03 UTC, squell requested changes
It seems to me like the difference between `fork` and `fork_for_test` is that `fork_for_test` simply adds some extra things for the test environment.

That I think is OK, but I would prefer to then add this to the `fork` function--otherwise there's the obvious risk that these functions start to diverge and then the test cases are not really exercising the "production code" anymore (we've had a similar case in the sudoers module in the past IIRC)

Commit [9f138ae](https://github.com/trifectatechfoundation/sudo-rs/pull/877/commits/9f138aea334ab667873b9055b6961b0ff2dbd5aa) looks good to me.

2024-10-14 15:12 UTC, bjorn3 commented
The regular fork is meant to be used to fork helper processes while the process is still single threaded. fork_for_test is exclusively for use in tests that need to create a new process for whatever reason. All fork_for_test usages should likely eventually be replaced with external helper binaries spawned by the respective test. As such I think they should stay separate.

2024-10-15 07:25 UTC, squell commented
Alright, so if the testcases that involve `fork` are not meant to test `fork` itself, I understand that having them separate can be beneficial. But can we then not apply DRY and express `fork_for_test` in terms of `fork`, i.e.

```rust
if ForkResult::Child == result {
        std::panic::set_hook(Box::new(|info| {
            use std::io::Write;
            let _ = writeln!(std::io::stderr(), "{info}");
            std::process::exit(101);
        }));
}

result
```

That would satisfy me; or is there a good reason not to?

(or equivalent with `if let`, `let else` or `match`, whatever is currently fashionable according to clippy 🤣)

2024-10-15 08:32 UTC, squell approved these changes

2024-10-15 08:35 UTC, merged