Specific Defaults
trifectatechfoundation/sudo-rs pull request #897
Opened 2024-10-29 13:46 UTC by squell

2025-02-10 14:33 UTC, bjorn3 requested changes

2025-02-10 14:33 UTC, bjorn3 commented on src/sudoers/ast.rs
> +#[repr(u32)]
Why is this `#[repr(u32)]`?

2025-02-10 14:33 UTC, bjorn3 commented on src/sudoers/ast.rs
> +                && stream.get_pos().1 - begin_pos.1 == "Defaults".len();
Using `stream.get_pos()` for anything other than error messages seems a bit fragile to me.

2025-02-10 14:33 UTC, bjorn3 commented on src/sudoers/mod.rs
> +/// Apply a specialization to the Setings object, used for "specific" Defaults
*Settings

2025-02-10 14:33 UTC, bjorn3 commented on src/sudoers/mod.rs
> +    customisers: CustomiserTable,
Maybe add a comment that this field is about `Default@host` and such?

2025-02-10 14:33 UTC, bjorn3 commented on src/sudoers/mod.rs
> +    fn specify_runas<User: UnixUser + PartialEq<User>>(&mut self, run_as: &User) {
Are `specify_host_and_user` and `specify_runas` ever called separately? If not maybe merge them?

2025-02-10 14:41 UTC, squell commented on src/sudoers/ast.rs
> +                && stream.get_pos().1 - begin_pos.1 == "Defaults".len();
Maybe it is. Let me think of an alternative and if I can't think of anything let's have a fight over this. :-)

2025-02-10 14:50 UTC, squell commented on src/sudoers/ast.rs
> +#[repr(u32)]
Look like I forgot to add the "rowhammer" mitigation discriminants in this enum.

2025-02-10 20:10 UTC, squell commented on src/sudoers/ast.rs
> +                && stream.get_pos().1 - begin_pos.1 == "Defaults".len();
I think the issue here why I choose this hack is that the token `Defaults` occurs in the same place where the parser will expect a `Spec<UserSpecifier>`, which will consume trailing white space; and then it's too late. The "begin_pos" info is availabe (since we want it for error correction anyway), so it's easy to use.

A less hacky fix would be to introduce a new type that "is either Defaults, Defaults@, etc. or a userspec" (by introducing a special token for "Defaults, Defaults@, Defaults:, Defaults> etc."). In essence the current code is already a bit hacky since it relies on the fact that `Defaults`, `Cmnd_Alias`, etc. can be parsed as a username and then "fixes the parsing" in post.

I'd prefer not  to do that now (will mean time wasted on a small obscure part of the parser instead of fixing larger issues) so I'll slap a NOTE here.

2025-02-11 10:45 UTC, bjorn3 approved these changes

2025-02-11 11:34 UTC, merged